export default {
    "aboutText": "Hi! I'm Bot for utilities. I work with Yandex.Money and I was developed during Yandex hackathon challenge.",
    "successfulAuthorizationText": "authentication is successful. What do you want to pay for?",
    "authorizationOfferText": "Dear, To pay for selected services you should be logged in into you Yandex.Money account.",
    "notAuthorizedText": "You are not logged in Yandex.Money. To pay for selected services you should be authorised in Yandex.Money.",
    "invalidPhotoText": "I can't recognize this photo. Please try again",
    "sendQRText": "Send me a photo of a QR-code please.",
    "canRecognizeQRText": "I can recognize QR-code. Send me a photo and I will try it!",
    "cannotRecognizeQRText": "I can't recognise QR-code. Send me the photo of QR-code please!",
    "cannotPayForOrganizationText": "I can't pay to this organization yet. But I can recognise this QR-code for you.",
    "failedToRecognizeCommandText": "Failed to recognise this command =(",
    "authorizeYandexMoneyText": "To authorize please follow the Yandex.Money link:",
    "endYandexMoneyAuthText": "Click confirm button when authorization will be completed.",
    "successfullyUpdatedTokenText": "Token is updated successfully.",
    "authorizationCompletedText": "Authorization completed successfully! You can use payment functions.",
    "failedToConfirmAuthorizationText": "Authorization failed. Click to the link and try again",
    "authorizationWarningText": "You can't pay without authorization. If you have any problems, please contact Yandex.Money or my Creator",
    "payPhoneStartText": "To replenish the balance sent me you number in format of 11 digits starting from 7. As well you can sent me any contact from you phonebook",
    "failedToRecognizePhoneText": "I can't recognize this number. Please, try again",
    "preparePayPhoneText": "Everything is ready to replenish the balance (500 rub is maximum). Нow much do you want to pay for",
    "failedToPayPhoneText": "I could not replenish the balance because of technical error.",
    "successfullyPayedPhoneText": "I've just replenished the telephone balance. Team work!",
    "invalidAmountText": "The sum is invalid.",
    "credentialsDialogText": "Enter your first and last names",
    "howMuchFundsToSpendText": "Нow much do you want to pay for PetroElectroSbut?",
    "lightCountersDialogText": "Enter your day and night meters data. Enter one value if you have a one-tariff meter.",
    "paymentErrorText": "Unfortunately, an error occurred while payment =(",
    "electricityPaymentSuccessText": "PetroElectroSbut payment success!",
    "yamoneyAuthorizationCompletedText": "You have successfully passed the authorization. Press CONFIRM in the Telegram app (lifetime of a temporary token - 1 min)",
    "useQRCodeMenuText": "Use QR code",
    "replenishBalanceMenuText": "Replenish the balance for mobile phone",
    "aboutMenuText": "About this bot",
    "authorizeMenuText": "Authorize in Yandex.Money",
    "confirmAuthMenuText": "Confirm authorization",
    "cancelMenuText": "Cancel"
}